### ISSUE TITLE
Provided sizes

### ISSUE THREAD

**Issue by bernikovich** [dDomovoj/Utility#1]
Not sure if this file (UIExtensionSize.swift) provides correct implementation. In my opinion this values can only be used as refrences. For example Apple can release new iPhone/iPad with new screen size, but with rounded corners - this will cause issue, when navigation bar (or tab bar) will be displayed in unsafe way. Custom navigationBar and tabBar implementations should do something like this: https://medium.com/@kahseng.lee123/creating-custom-navigation-bar-tab-bar-for-iphone-x-f03b1e1827d3

**Comment by dDomovoj** [comment]
That's right, thank you
